apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/aenright79e/gitops-demo.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: gitops-demo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true