apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-deployment
spec:
  selector:
    matchLabels:
      app: gitops-demo
  replicas: 3
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
      - name: gitops-demo
        image: aenright79e/gitops-demo-app:1.4
        ports:
        - containerPort: 80