apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
spec:
  selector:
    matchLabels:
      app: gitops-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
      - name: gitops-demo
        image: aenright78e/gitops-demo-app:1.7
        ports:
        - containerPort: 80