apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-depl
spec:
  selector:
    matchLabels:
      app: gitops-demo
  replicas: 4
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
      - name: gitops-demo
        image: aenright78e/gitops-demo-app:1.8
        ports:
        - containerPort: 80