apiVersion: v1
kind: Service
metadata:
  name: gitops-demo-service
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30099
    targetPort: 8080
  selector:
    app: gitops-demo