apiVersion: v1
kind: Service
metadata:
  name: gitops-demo-service
spec:
  selector:
    app: gitops-demo
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    nodePort:30808
    targetPort: 8080